### ISSUE TITLE
setup modelio-open-source-4.0.0-macosx.cocoa.x86_64.tar.gz is error

### ISSUE THREAD

**Issue by yxtwang** [ambpro/modelio-jdl-studio#1]
1: my is mac 
2: setup log.

2019-11-21 22:18:47,710 INFO  l.w.PluginLogger - Changing log level from ERROR to DEBUG
2019-11-21 22:18:47,713 DEBUG .m.a.preferences - Initializing 'org.modelio.app.preferences' plugin preferences ...
2019-11-21 22:18:47,716 DEBUG .m.a.preferences -  - Initializing default values from 'org.modelio.admtool'...
2019-11-21 22:18:47,716 DEBUG .m.a.preferences -    - default pref value 'Log.LogLevel'='3'
2019-11-21 22:18:47,716 DEBUG .m.a.preferences -    - default pref value 'AdmTools.Show'='false'
2019-11-21 22:18:47,716 DEBUG .m.a.preferences -  - Initializing default values from 'org.modelio.app.modules'...
2019-11-21 22:18:47,716 DEBUG .m.a.preferences -    - default pref value 'ModuleCatalog.ShowCompatible'='true'
2019-11-21 22:18:47,717 DEBUG .m.a.preferences -    - default pref value 'ModuleCatalog.ShowLatest'='true'
2019-11-21 22:18:47,717 DEBUG .m.a.preferences -  - Initializing default values from 'org.modelio.app.update.ext'...
2019-11-21 22:18:47,717 DEBUG .m.a.preferences -    - default pref value 'Update.Site'='https://www.modelio.org/updates'
2019-11-21 22:18:47,717 INFO  l.w.PluginLogger - Changing log level from DEBUG to ERROR
2019-11-21 22:18:47,723 DEBUG l.w.PluginLogger - Leaving DEBUG log level
java.lang.Throwable: Log level change stack trace
        at org.modelio.utils.log.writers.PluginLogger.setLogLevel(PluginLogger.java:297)
        at org.modelio.app.preferences.plugin.AppPrefsPreferenceInitializer.initializeDefaultPreferences(AppPrefsPreferenceInitializer.java:82)
        at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:301)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:304)
        at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:134)
        at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:375)
        at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:225)
        at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:279)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:370)
        at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:623)
        at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:766)
        at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:41)
        at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:77)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.getDefaultPreferences(ScopedPreferenceStore.java:237)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.getPreferenceNodes(ScopedPreferenceStore.java:268)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.internalGet(ScopedPreferenceStore.java:416)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.getInt(ScopedPreferenceStore.java:434)
        at org.modelio.app.preferences.LogLevelUpdater.setLogLevelFromPreferences(LogLevelUpdater.java:41)
        at org.modelio.app.ui.plugin.AppUi.initializeLogLevel(AppUi.java:127)
        at org.modelio.app.ui.plugin.AppUi.start(AppUi.java:113)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:815)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:808)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:765)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
        at org.eclipse.osgi.container.Module.doStart(Module.java:589)
        at org.eclipse.osgi.container.Module.start(Module.java:457)

**Comment by yxtwang** [comment]
![image](https://user-images.githubusercontent.com/2188478/69347127-eab82180-0cae-11ea-88d7-0d85b6f453cd.png)

**Comment by yxtwang** [comment]
is ok . thks

**Comment by ambpro** [comment]
@yxtwang, The current github bug tracker is dedicated for the `modelio-jdl-studio` module.
In case you have an issue with `modelio-open-source-4.0.0`, please feel free to submit it directly at the [Redmine Bug Tracker](https://forge.modelio.org/projects/modelio3/issues) forge.

**Comment by ambpro** [comment]
Closing the issue!

**Comment by yxtwang** [comment]
thks
